### ISSUE TITLE
Failed to load game data from patches

### ISSUE THREAD

**Issue by Logomotep** [darthRebel/swcnoops#17]
Hello, 
I have problems starting the private server in VsCode, yesterday it worked, it showed the port, but today it gave an error "Failed to load game data from patches" I'm not that experienced, so I don't know what to do. Before that, I only had problems redirecting the game client, but that didn't work.
![Screenshot 2022-06-25 135324](https://user-images.githubusercontent.com/78428729/175772499-0c88115c-b6bf-47d0-ac54-6f551dee0cbe.png)

**Comment by darthRebel** [comment]
I will post exact instructions later tonight. I tried visual studio code but it didn't agree with me, so my instructions will be with intelliJ. I have not tried it from scratch so maybe I have left something out, but it should work. As judging by that error it is the config that might be wrong to the patch files. Are you doing this on windows I assume.

**Comment by Logomotep** [comment]
Yes, I'm doing this on Windows

**Comment by darthRebel** [comment]
Hi,

thanks the problem was the config code was out of sync with the files in the project.
I have corrected that now, as well as included some steps if using through IntelliJ which was what I did to verify that it all works again.
