### ISSUE TITLE
SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException 

### ISSUE THREAD

**Issue by mcneb10** [darthRebel/swcnoops#21]
When I try to get the game client to connect, I get this error in the fiddler log:
`14:52:49:5428 HTTPSLint> Warning: ClientHello record was 508 bytes long. Some servers have problems with ClientHello's greater than 255 bytes. https://github.com/ssllabs/research/wiki/Long-Handshake-Intolerance
14:52:49:5738 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < An unknown error occurred while processing the certificate for pipe (CN=*.apps.starwarscommander.com, O=DO_NOT_TRUST, OU=Created by http://www.fiddler2.com).`
After I exit the game and go back in, the client refuses to connect at all.
To fix this I had to delete the app, flush the DNS cache (switching airplane mode on and off), and the reinstall the app.
The game client does not connect
Any ideas?

**Comment by darthRebel** [comment]
Have never seen that before. What is your setup? Is this an emulator, or a real device? The first thing is to make sure that you are connected to fiddler and that is all working.

**Comment by mcneb10** [comment]
I heard something about android not trusting a root certificate after version 6.0. Im trying that version now.

**Comment by darthRebel** [comment]
I have a feeling from android 6+ it has certificate pinning, as I had to get around that by modifying the APK manifest file before fiddler worked on my device which is android 8. The game does work on android 5, here is a screen shot of it running on memu. My setup for dev is latest memu emulator, with android 5.1 using Google Pixel 2 profile.

![image](https://user-images.githubusercontent.com/107359895/176008179-09f11798-4b08-4b1d-8001-c59864930fd7.png)

**Comment by mcneb10** [comment]
i tried modifying the manifest file, but i couldn't compile it back into it's binary form. do you know how to do that?

**Comment by darthRebel** [comment]
Shouldn't need to do anything special to the androidmanifest. It would be the same as what you did with decompiling apk, modify, recompile, sign and realign. Hopefully it's not a new android security thing. Which emulator is this that is giving you this invalid manifest error? I can give it a try.

**Comment by mcneb10** [comment]
I was using the android studio emulator with android 10

**Comment by darthRebel** [comment]
If you like you can direct chat me on Reddit.
