### ISSUE TITLE
Squad member count inconsistency

### ISSUE THREAD

**Issue by DaveCMo** [darthRebel/swcnoops#67]
Squad member count not currently accurate:
![image](https://user-images.githubusercontent.com/30052481/185903764-c28618be-8479-41a3-83fc-a8bac35fb3b8.png)

**Comment by darthRebel** [comment]
The first time if it's not accurate it's because the cached data is out of sync with the SQL, if afterwards it's not same as the DB it's because the client caches squad info and only goes back to the server after X minutes.

**Comment by darthRebel** [comment]
Can confirm it is to do with client caching.
